sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install tox-travis
  - pip install coveralls

script:
  - tox
  - coverage run --source=cryptoparams setup.py test

after_success:
  - coveralls